### ISSUE TITLE
http://localhost:3000/translations fails on Windows

### ISSUE THREAD

**Issue by cdvcz** [redrick/redis_dictionary#2]
![screenshot_1](https://f.cloud.github.com/assets/3787027/1235865/d0a492d8-29b1-11e3-926f-1d713380ce19.png)

[TR]

**Comment by redrick** [comment]
there you go, fixed with https://github.com/redrick/i18n_dashboard/commit/e083d9547727a9cbcd2c4dfa4f80735b0ea7db1d

seems windows does not like coffeeescript out of the box :(
